
// post
export const SET_POSTS = 'SET_POSTS'
export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CURRENT_POST = 'SET_CURRENT_POST'
export const UPDATE_POST_IN_LIST = 'UPDATE_POST_IN_LIST'
export const UPDATE_MODAL_POST = 'UPDATE_MODAL_POST'
export const RESET_FORM = 'RESET_FORM'

//flight
export const SET_DEPARTURE_FLIGHT = 'SET_DEPARTURE_FLIGHT'
export const SET_RETURN_FLIGHT = 'SET_RETURN_FLIGHT'